/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DogDogIdRouteImport } from './routes/dog.$dogId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DogDogIdRoute = DogDogIdRouteImport.update({
  id: '/dog/$dogId',
  path: '/dog/$dogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dog/$dogId': typeof DogDogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dog/$dogId': typeof DogDogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dog/$dogId': typeof DogDogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dog/$dogId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dog/$dogId'
  id: '__root__' | '/' | '/dog/$dogId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DogDogIdRoute: typeof DogDogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dog/$dogId': {
      id: '/dog/$dogId'
      path: '/dog/$dogId'
      fullPath: '/dog/$dogId'
      preLoaderRoute: typeof DogDogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DogDogIdRoute: DogDogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
